spring:

  application:
    name: MyProject

  jpa:
    show-sql: false



jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refreshExpiration: ${JWT_REFRESH_EXPIRATION}

  threads:
    virtual:
      enabled: true

gemini:
  api:
    key: ${GEMINI_API_KEY}
    baseUrl: https://generativelanguage.googleapis.com/
