spring:
  profiles:
    active: local

  application:
    name: MyProject

  jpa:
    hibernate:
      ddl-auto: validate # update, create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true



jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refreshExpiration: ${JWT_REFRESH_EXPIRATION}

  threads:
    virtual:
      enabled: true

gemini:
  api:
    key: ${GEMINI_API_KEY}
    baseUrl: https://generativelanguage.googleapis.com/
