spring:
  config:
    import: optional:file:.env[.properties]

  profiles:
    active: local

  application:
    name: MyProject

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refreshExpiration: ${JWT_REFRESH_EXPIRATION}

  threads:
    virtual:
      enabled: true
